// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::foreign_account_type::ForeignAccount;

/// Table handle for the table `foreign_account`.
///
/// Obtain a handle from the [`ForeignAccountTableAccess::foreign_account`]
/// method on [`super::RemoteTables`], like `ctx.db.foreign_account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.foreign_account().on_insert(...)`.
pub struct ForeignAccountTableHandle<'ctx> {
	imp: __sdk::TableHandle<ForeignAccount>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `foreign_account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ForeignAccountTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`ForeignAccountTableHandle`], which mediates access to the
	/// table `foreign_account`.
	fn foreign_account(&self) -> ForeignAccountTableHandle<'_>;
}

impl ForeignAccountTableAccess for super::RemoteTables {
	fn foreign_account(&self) -> ForeignAccountTableHandle<'_> {
		ForeignAccountTableHandle {
			imp: self.imp.get_table::<ForeignAccount>("foreign_account"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct ForeignAccountInsertCallbackId(__sdk::CallbackId);
pub struct ForeignAccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ForeignAccountTableHandle<'ctx> {
	type DeleteCallbackId = ForeignAccountDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = ForeignAccountInsertCallbackId;
	type Row = ForeignAccount;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = ForeignAccount> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ForeignAccountInsertCallbackId {
		ForeignAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: ForeignAccountInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ForeignAccountDeleteCallbackId {
		ForeignAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: ForeignAccountDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<ForeignAccount>("foreign_account");
	_table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct ForeignAccountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ForeignAccountTableHandle<'ctx> {
	type UpdateCallbackId = ForeignAccountUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> ForeignAccountUpdateCallbackId {
		ForeignAccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: ForeignAccountUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ForeignAccount>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<ForeignAccount>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `foreign_account`,
/// which allows point queries on the field of the same name
/// via the [`ForeignAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.foreign_account().id().find(...)`.
pub struct ForeignAccountIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<ForeignAccount, String>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ForeignAccountTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `foreign_account`.
	pub fn id(&self) -> ForeignAccountIdUnique<'ctx> {
		ForeignAccountIdUnique {
			imp:     self.imp.get_unique_constraint::<String>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> ForeignAccountIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &String) -> Option<ForeignAccount> {
		self.imp.find(col_val)
	}
}
