// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LinkForeignAccountArgs {
	pub ext_account_id: String,
}

impl From<LinkForeignAccountArgs> for super::Reducer {
	fn from(args: LinkForeignAccountArgs) -> Self {
		Self::LinkForeignAccount {
			ext_account_id: args.ext_account_id,
		}
	}
}

impl __sdk::InModule for LinkForeignAccountArgs {
	type Module = super::RemoteModule;
}

pub struct LinkForeignAccountCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `link_foreign_account`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait link_foreign_account {
	/// Request that the remote module invoke the reducer `link_foreign_account`
	/// to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_link_foreign_account`] callbacks.
	fn link_foreign_account(&self, ext_account_id: String) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `link_foreign_account`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`LinkForeignAccountCallbackId`] can be passed to
	/// [`Self::remove_on_link_foreign_account`] to cancel the callback.
	fn on_link_foreign_account(
		&self, callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
	) -> LinkForeignAccountCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_link_foreign_account`], causing it not to run in the future.
	fn remove_on_link_foreign_account(&self, callback: LinkForeignAccountCallbackId);
}

impl link_foreign_account for super::RemoteReducers {
	fn link_foreign_account(&self, ext_account_id: String) -> __sdk::Result<()> {
		self.imp
			.call_reducer("link_foreign_account", LinkForeignAccountArgs {
				ext_account_id,
			})
	}

	fn on_link_foreign_account(
		&self, mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
	) -> LinkForeignAccountCallbackId {
		LinkForeignAccountCallbackId(self.imp.on_reducer(
			"link_foreign_account",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer: super::Reducer::LinkForeignAccount { ext_account_id },
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, ext_account_id)
			}),
		))
	}

	fn remove_on_link_foreign_account(&self, callback: LinkForeignAccountCallbackId) {
		self.imp
			.remove_on_reducer("link_foreign_account", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `link_foreign_account`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_link_foreign_account {
	/// Set the call-reducer flags for the reducer `link_foreign_account` to
	/// `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn link_foreign_account(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_link_foreign_account for super::SetReducerFlags {
	fn link_foreign_account(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("link_foreign_account", flags);
	}
}
