// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChannelMetadata {
	pub description: Option<String>,
	pub avatar_url:  Option<String>,
	pub alt_aliases: Option<Vec<String>>,
}

impl __sdk::InModule for ChannelMetadata {
	type Module = super::RemoteModule;
}
