// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::external_actor_type::ExternalActor;

/// Table handle for the table `external_actor`.
///
/// Obtain a handle from the [`ExternalActorTableAccess::external_actor`] method
/// on [`super::RemoteTables`], like `ctx.db.external_actor()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.external_actor().on_insert(...)`.
pub struct ExternalActorTableHandle<'ctx> {
	imp: __sdk::TableHandle<ExternalActor>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `external_actor`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ExternalActorTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`ExternalActorTableHandle`], which mediates access to the
	/// table `external_actor`.
	fn external_actor(&self) -> ExternalActorTableHandle<'_>;
}

impl ExternalActorTableAccess for super::RemoteTables {
	fn external_actor(&self) -> ExternalActorTableHandle<'_> {
		ExternalActorTableHandle {
			imp: self.imp.get_table::<ExternalActor>("external_actor"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct ExternalActorInsertCallbackId(__sdk::CallbackId);
pub struct ExternalActorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ExternalActorTableHandle<'ctx> {
	type DeleteCallbackId = ExternalActorDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = ExternalActorInsertCallbackId;
	type Row = ExternalActor;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = ExternalActor> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ExternalActorInsertCallbackId {
		ExternalActorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: ExternalActorInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ExternalActorDeleteCallbackId {
		ExternalActorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: ExternalActorDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<ExternalActor>("external_actor");
	_table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct ExternalActorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ExternalActorTableHandle<'ctx> {
	type UpdateCallbackId = ExternalActorUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> ExternalActorUpdateCallbackId {
		ExternalActorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: ExternalActorUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ExternalActor>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<ExternalActor>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `external_actor`,
/// which allows point queries on the field of the same name
/// via the [`ExternalActorIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.external_actor().id().find(...)`.
pub struct ExternalActorIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<ExternalActor, String>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ExternalActorTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `external_actor`.
	pub fn id(&self) -> ExternalActorIdUnique<'ctx> {
		ExternalActorIdUnique {
			imp:     self.imp.get_unique_constraint::<String>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> ExternalActorIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &String) -> Option<ExternalActor> {
		self.imp.find(col_val)
	}
}
