// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::external_account_type::ExternalAccount;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `external_account`.
///
/// Obtain a handle from the [`ExternalAccountTableAccess::external_account`] method on [`super::RemoteTables`],
/// like `ctx.db.external_account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.external_account().on_insert(...)`.
pub struct ExternalAccountTableHandle<'ctx> {
	imp: __sdk::TableHandle<ExternalAccount>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `external_account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ExternalAccountTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`ExternalAccountTableHandle`], which mediates access to the table `external_account`.
	fn external_account(&self) -> ExternalAccountTableHandle<'_>;
}

impl ExternalAccountTableAccess for super::RemoteTables {
	fn external_account(&self) -> ExternalAccountTableHandle<'_> {
		ExternalAccountTableHandle {
			imp: self.imp.get_table::<ExternalAccount>("external_account"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct ExternalAccountInsertCallbackId(__sdk::CallbackId);
pub struct ExternalAccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ExternalAccountTableHandle<'ctx> {
	type Row = ExternalAccount;
	type EventContext = super::EventContext;

	fn count(&self) -> u64 {
		self.imp.count()
	}
	fn iter(&self) -> impl Iterator<Item = ExternalAccount> + '_ {
		self.imp.iter()
	}

	type InsertCallbackId = ExternalAccountInsertCallbackId;

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ExternalAccountInsertCallbackId {
		ExternalAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: ExternalAccountInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	type DeleteCallbackId = ExternalAccountDeleteCallbackId;

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ExternalAccountDeleteCallbackId {
		ExternalAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: ExternalAccountDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<ExternalAccount>("external_account");
	_table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct ExternalAccountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ExternalAccountTableHandle<'ctx> {
	type UpdateCallbackId = ExternalAccountUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> ExternalAccountUpdateCallbackId {
		ExternalAccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: ExternalAccountUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ExternalAccount>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<ExternalAccount>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `external_account`,
/// which allows point queries on the field of the same name
/// via the [`ExternalAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.external_account().id().find(...)`.
pub struct ExternalAccountIdUnique<'ctx> {
	imp: __sdk::UniqueConstraintHandle<ExternalAccount, String>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ExternalAccountTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `external_account`.
	pub fn id(&self) -> ExternalAccountIdUnique<'ctx> {
		ExternalAccountIdUnique {
			imp: self.imp.get_unique_constraint::<String>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> ExternalAccountIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &String) -> Option<ExternalAccount> {
		self.imp.find(col_val)
	}
}
