// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::social_profile_metadata_type::SocialProfileMetadata;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SocialProfile {
	pub id:               u64,
	pub owner_account_id: __sdk::Identity,
	pub metadata:         SocialProfileMetadata,
}

impl __sdk::InModule for SocialProfile {
	type Module = super::RemoteModule;
}
