[workspace]
members = ["modules/crownest", "packages/crowlink-rs", "services/telecrow"]
resolver = "3"


[workspace.package]
authors = ["Carina.Akaia.org <cvo.akaia@gmail.com>"]
keywords = ["akaia-labs", "communication", "community", "knowledge base"]


[profile.release]
opt-level = "z"
lto = true
panic = "abort"
overflow-checks = true


[workspace.dependencies]
# crow.d
crowlink-rs = { path = "packages/crowlink-rs" }

# External packages
dotenvy = "0.15.7"
hex = "0.4"
log = "0.4"
pretty_env_logger = "0.5"
spacetimedb = "1.1.0"
spacetimedb-sdk = "1.0"
teloxide = { version = "0.15.0", features = ["macros"] }
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
# wasm-opt = "0.116.1"
