[workspace]
members = ["modules/crownest", "packages/crowlink-rs", "services/telecrow"]
resolver = "3"


[workspace.package]
authors = ["Carina.Akaia.org <cvo.akaia@gmail.com>"]
keywords = ["akaia-labs", "communication", "community", "knowledge base"]


[profile.release]
opt-level = "z"
lto = true
panic = "abort"
overflow-checks = true


[workspace.dependencies]
# crow.d
crowlink-rs = { path = "packages/crowlink-rs" }

# External packages
hex = "0.4"
log = "0.4"
spacetimedb = "1.1.0"
spacetimedb-sdk = "1.0"
# wasm-opt = "0.116.1"
