// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::{
	native_account_local_role_type::NativeAccountLocalRole, native_account_type::NativeAccount,
};

/// Table handle for the table `native_account`.
///
/// Obtain a handle from the [`NativeAccountTableAccess::native_account`] method
/// on [`super::RemoteTables`], like `ctx.db.native_account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.native_account().on_insert(...)`.
pub struct NativeAccountTableHandle<'ctx> {
	imp: __sdk::TableHandle<NativeAccount>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `native_account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NativeAccountTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`NativeAccountTableHandle`], which mediates access to the
	/// table `native_account`.
	fn native_account(&self) -> NativeAccountTableHandle<'_>;
}

impl NativeAccountTableAccess for super::RemoteTables {
	fn native_account(&self) -> NativeAccountTableHandle<'_> {
		NativeAccountTableHandle {
			imp: self.imp.get_table::<NativeAccount>("native_account"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct NativeAccountInsertCallbackId(__sdk::CallbackId);
pub struct NativeAccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NativeAccountTableHandle<'ctx> {
	type DeleteCallbackId = NativeAccountDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = NativeAccountInsertCallbackId;
	type Row = NativeAccount;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = NativeAccount> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> NativeAccountInsertCallbackId {
		NativeAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: NativeAccountInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> NativeAccountDeleteCallbackId {
		NativeAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: NativeAccountDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<NativeAccount>("native_account");
	_table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
	_table.add_unique_constraint::<String>("callsign", |row| &row.callsign);
	_table.add_unique_constraint::<u64>("profile_id", |row| &row.profile_id);
}
pub struct NativeAccountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NativeAccountTableHandle<'ctx> {
	type UpdateCallbackId = NativeAccountUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> NativeAccountUpdateCallbackId {
		NativeAccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: NativeAccountUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<NativeAccount>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<NativeAccount>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `native_account`,
/// which allows point queries on the field of the same name
/// via the [`NativeAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.native_account().id().find(...)`.
pub struct NativeAccountIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<NativeAccount, __sdk::Identity>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NativeAccountTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `native_account`.
	pub fn id(&self) -> NativeAccountIdUnique<'ctx> {
		NativeAccountIdUnique {
			imp:     self.imp.get_unique_constraint::<__sdk::Identity>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> NativeAccountIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &__sdk::Identity) -> Option<NativeAccount> {
		self.imp.find(col_val)
	}
}

/// Access to the `callsign` unique index on the table `native_account`,
/// which allows point queries on the field of the same name
/// via the [`NativeAccountCallsignUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.native_account().callsign().find(...)`.
pub struct NativeAccountCallsignUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<NativeAccount, String>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NativeAccountTableHandle<'ctx> {
	/// Get a handle on the `callsign` unique index on the table
	/// `native_account`.
	pub fn callsign(&self) -> NativeAccountCallsignUnique<'ctx> {
		NativeAccountCallsignUnique {
			imp:     self.imp.get_unique_constraint::<String>("callsign"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> NativeAccountCallsignUnique<'ctx> {
	/// Find the subscribed row whose `callsign` column value is equal to
	/// `col_val`, if such a row is present in the client cache.
	pub fn find(&self, col_val: &String) -> Option<NativeAccount> {
		self.imp.find(col_val)
	}
}

/// Access to the `profile_id` unique index on the table `native_account`,
/// which allows point queries on the field of the same name
/// via the [`NativeAccountProfileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.native_account().profile_id().find(...)`.
pub struct NativeAccountProfileIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<NativeAccount, u64>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NativeAccountTableHandle<'ctx> {
	/// Get a handle on the `profile_id` unique index on the table
	/// `native_account`.
	pub fn profile_id(&self) -> NativeAccountProfileIdUnique<'ctx> {
		NativeAccountProfileIdUnique {
			imp:     self.imp.get_unique_constraint::<u64>("profile_id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> NativeAccountProfileIdUnique<'ctx> {
	/// Find the subscribed row whose `profile_id` column value is equal to
	/// `col_val`, if such a row is present in the client cache.
	pub fn find(&self, col_val: &u64) -> Option<NativeAccount> {
		self.imp.find(col_val)
	}
}
