[package]
name = "crowchat"
description = "Akaia Labs crow.d chat server"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib"]


[dependencies]
spacetimedb.workspace = true
log.workspace = true
