// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::{actor_profile_metadata_type::ActorProfileMetadata, actor_profile_type::ActorProfile};

/// Table handle for the table `actor_profile`.
///
/// Obtain a handle from the [`ActorProfileTableAccess::actor_profile`] method
/// on [`super::RemoteTables`], like `ctx.db.actor_profile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.actor_profile().on_insert(...)`.
pub struct ActorProfileTableHandle<'ctx> {
	imp: __sdk::TableHandle<ActorProfile>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `actor_profile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActorProfileTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`ActorProfileTableHandle`], which mediates access to the table
	/// `actor_profile`.
	fn actor_profile(&self) -> ActorProfileTableHandle<'_>;
}

impl ActorProfileTableAccess for super::RemoteTables {
	fn actor_profile(&self) -> ActorProfileTableHandle<'_> {
		ActorProfileTableHandle {
			imp: self.imp.get_table::<ActorProfile>("actor_profile"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct ActorProfileInsertCallbackId(__sdk::CallbackId);
pub struct ActorProfileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ActorProfileTableHandle<'ctx> {
	type DeleteCallbackId = ActorProfileDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = ActorProfileInsertCallbackId;
	type Row = ActorProfile;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = ActorProfile> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ActorProfileInsertCallbackId {
		ActorProfileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: ActorProfileInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ActorProfileDeleteCallbackId {
		ActorProfileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: ActorProfileDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<ActorProfile>("actor_profile");
	_table.add_unique_constraint::<i128>("id", |row| &row.id);
}
pub struct ActorProfileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActorProfileTableHandle<'ctx> {
	type UpdateCallbackId = ActorProfileUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> ActorProfileUpdateCallbackId {
		ActorProfileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: ActorProfileUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ActorProfile>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<ActorProfile>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `actor_profile`,
/// which allows point queries on the field of the same name
/// via the [`ActorProfileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.actor_profile().id().find(...)`.
pub struct ActorProfileIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<ActorProfile, i128>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActorProfileTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `actor_profile`.
	pub fn id(&self) -> ActorProfileIdUnique<'ctx> {
		ActorProfileIdUnique {
			imp:     self.imp.get_unique_constraint::<i128>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> ActorProfileIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &i128) -> Option<ActorProfile> {
		self.imp.find(col_val)
	}
}
