// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::channel_metadata_type::ChannelMetadata;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateSubchannelArgs {
	pub alias:           String,
	pub metadata:        Option<ChannelMetadata>,
	pub superchannel_id: String,
}

impl From<CreateSubchannelArgs> for super::Reducer {
	fn from(args: CreateSubchannelArgs) -> Self {
		Self::CreateSubchannel {
			alias:           args.alias,
			metadata:        args.metadata,
			superchannel_id: args.superchannel_id,
		}
	}
}

impl __sdk::InModule for CreateSubchannelArgs {
	type Module = super::RemoteModule;
}

pub struct CreateSubchannelCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_subchannel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_subchannel {
	/// Request that the remote module invoke the reducer `create_subchannel` to
	/// run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_create_subchannel`] callbacks.
	fn create_subchannel(
		&self, alias: String, metadata: Option<ChannelMetadata>, superchannel_id: String,
	) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `create_subchannel`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`CreateSubchannelCallbackId`] can be passed to
	/// [`Self::remove_on_create_subchannel`] to cancel the callback.
	fn on_create_subchannel(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &String, &Option<ChannelMetadata>, &String)
		+ Send
		+ 'static,
	) -> CreateSubchannelCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_create_subchannel`], causing it not to run in the future.
	fn remove_on_create_subchannel(&self, callback: CreateSubchannelCallbackId);
}

impl create_subchannel for super::RemoteReducers {
	fn create_subchannel(
		&self, alias: String, metadata: Option<ChannelMetadata>, superchannel_id: String,
	) -> __sdk::Result<()> {
		self.imp
			.call_reducer("create_subchannel", CreateSubchannelArgs {
				alias,
				metadata,
				superchannel_id,
			})
	}

	fn on_create_subchannel(
		&self,
		mut callback: impl FnMut(
			&super::ReducerEventContext,
			&String,
			&Option<ChannelMetadata>,
			&String,
		) + Send
		+ 'static,
	) -> CreateSubchannelCallbackId {
		CreateSubchannelCallbackId(self.imp.on_reducer(
			"create_subchannel",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer:
								super::Reducer::CreateSubchannel {
									alias,
									metadata,
									superchannel_id,
								},
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, alias, metadata, superchannel_id)
			}),
		))
	}

	fn remove_on_create_subchannel(&self, callback: CreateSubchannelCallbackId) {
		self.imp.remove_on_reducer("create_subchannel", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `create_subchannel`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_create_subchannel {
	/// Set the call-reducer flags for the reducer `create_subchannel` to
	/// `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn create_subchannel(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_subchannel for super::SetReducerFlags {
	fn create_subchannel(&self, flags: __ws::CallReducerFlags) {
		self.imp.set_call_reducer_flags("create_subchannel", flags);
	}
}
