// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::direct_channel_type::DirectChannel;

/// Table handle for the table `direct_channel`.
///
/// Obtain a handle from the [`DirectChannelTableAccess::direct_channel`] method
/// on [`super::RemoteTables`], like `ctx.db.direct_channel()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.direct_channel().on_insert(...)`.
pub struct DirectChannelTableHandle<'ctx> {
	imp: __sdk::TableHandle<DirectChannel>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `direct_channel`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DirectChannelTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`DirectChannelTableHandle`], which mediates access to the
	/// table `direct_channel`.
	fn direct_channel(&self) -> DirectChannelTableHandle<'_>;
}

impl DirectChannelTableAccess for super::RemoteTables {
	fn direct_channel(&self) -> DirectChannelTableHandle<'_> {
		DirectChannelTableHandle {
			imp: self.imp.get_table::<DirectChannel>("direct_channel"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct DirectChannelInsertCallbackId(__sdk::CallbackId);
pub struct DirectChannelDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DirectChannelTableHandle<'ctx> {
	type DeleteCallbackId = DirectChannelDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = DirectChannelInsertCallbackId;
	type Row = DirectChannel;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = DirectChannel> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> DirectChannelInsertCallbackId {
		DirectChannelInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: DirectChannelInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> DirectChannelDeleteCallbackId {
		DirectChannelDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: DirectChannelDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<DirectChannel>("direct_channel");
	_table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct DirectChannelUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DirectChannelTableHandle<'ctx> {
	type UpdateCallbackId = DirectChannelUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> DirectChannelUpdateCallbackId {
		DirectChannelUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: DirectChannelUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DirectChannel>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<DirectChannel>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `direct_channel`,
/// which allows point queries on the field of the same name
/// via the [`DirectChannelIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.direct_channel().id().find(...)`.
pub struct DirectChannelIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<DirectChannel, String>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DirectChannelTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `direct_channel`.
	pub fn id(&self) -> DirectChannelIdUnique<'ctx> {
		DirectChannelIdUnique {
			imp:     self.imp.get_unique_constraint::<String>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> DirectChannelIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &String) -> Option<DirectChannel> {
		self.imp.find(col_val)
	}
}
