// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::external_authentication_request_type::ExternalAuthenticationRequest;

/// Table handle for the table `external_authentication_request`.
///
/// Obtain a handle from the
/// [`ExternalAuthenticationRequestTableAccess::external_authentication_request`]
/// method on [`super::RemoteTables`], like `ctx.db.
/// external_authentication_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.external_authentication_request().on_insert(...)`.
pub struct ExternalAuthenticationRequestTableHandle<'ctx> {
	imp: __sdk::TableHandle<ExternalAuthenticationRequest>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `external_authentication_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ExternalAuthenticationRequestTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`ExternalAuthenticationRequestTableHandle`], which mediates
	/// access to the table `external_authentication_request`.
	fn external_authentication_request(&self) -> ExternalAuthenticationRequestTableHandle<'_>;
}

impl ExternalAuthenticationRequestTableAccess for super::RemoteTables {
	fn external_authentication_request(&self) -> ExternalAuthenticationRequestTableHandle<'_> {
		ExternalAuthenticationRequestTableHandle {
			imp: self
				.imp
				.get_table::<ExternalAuthenticationRequest>("external_authentication_request"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct ExternalAuthenticationRequestInsertCallbackId(__sdk::CallbackId);
pub struct ExternalAuthenticationRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ExternalAuthenticationRequestTableHandle<'ctx> {
	type DeleteCallbackId = ExternalAuthenticationRequestDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = ExternalAuthenticationRequestInsertCallbackId;
	type Row = ExternalAuthenticationRequest;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = ExternalAuthenticationRequest> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ExternalAuthenticationRequestInsertCallbackId {
		ExternalAuthenticationRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: ExternalAuthenticationRequestInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> ExternalAuthenticationRequestDeleteCallbackId {
		ExternalAuthenticationRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: ExternalAuthenticationRequestDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache
		.get_or_make_table::<ExternalAuthenticationRequest>("external_authentication_request");
	_table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ExternalAuthenticationRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ExternalAuthenticationRequestTableHandle<'ctx> {
	type UpdateCallbackId = ExternalAuthenticationRequestUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> ExternalAuthenticationRequestUpdateCallbackId {
		ExternalAuthenticationRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: ExternalAuthenticationRequestUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ExternalAuthenticationRequest>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse(
			"TableUpdate<ExternalAuthenticationRequest>",
			"TableUpdate",
		)
		.with_cause(e)
		.into()
	})
}

/// Access to the `id` unique index on the table
/// `external_authentication_request`, which allows point queries on the field
/// of the same name via the [`ExternalAuthenticationRequestIdUnique::find`]
/// method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.external_authentication_request().id().find(...)`.
pub struct ExternalAuthenticationRequestIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<ExternalAuthenticationRequest, u64>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ExternalAuthenticationRequestTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table
	/// `external_authentication_request`.
	pub fn id(&self) -> ExternalAuthenticationRequestIdUnique<'ctx> {
		ExternalAuthenticationRequestIdUnique {
			imp:     self.imp.get_unique_constraint::<u64>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> ExternalAuthenticationRequestIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &u64) -> Option<ExternalAuthenticationRequest> {
		self.imp.find(col_val)
	}
}
