// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::external_authentication_request_expiry_schedule_type::ExternalAuthenticationRequestExpirySchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ScheduledDeleteExtAuthReqArgs {
	pub args: ExternalAuthenticationRequestExpirySchedule,
}

impl From<ScheduledDeleteExtAuthReqArgs> for super::Reducer {
	fn from(args: ScheduledDeleteExtAuthReqArgs) -> Self {
		Self::ScheduledDeleteExtAuthReq { args: args.args }
	}
}

impl __sdk::InModule for ScheduledDeleteExtAuthReqArgs {
	type Module = super::RemoteModule;
}

pub struct ScheduledDeleteExtAuthReqCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `scheduled_delete_ext_auth_req`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait scheduled_delete_ext_auth_req {
	/// Request that the remote module invoke the reducer
	/// `scheduled_delete_ext_auth_req` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_scheduled_delete_ext_auth_req`] callbacks.
	fn scheduled_delete_ext_auth_req(
		&self, args: ExternalAuthenticationRequestExpirySchedule,
	) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `scheduled_delete_ext_auth_req`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`ScheduledDeleteExtAuthReqCallbackId`] can be passed to
	/// [`Self::remove_on_scheduled_delete_ext_auth_req`] to cancel the
	/// callback.
	fn on_scheduled_delete_ext_auth_req(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &ExternalAuthenticationRequestExpirySchedule)
		+ Send
		+ 'static,
	) -> ScheduledDeleteExtAuthReqCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_scheduled_delete_ext_auth_req`], causing it not to run in
	/// the future.
	fn remove_on_scheduled_delete_ext_auth_req(
		&self, callback: ScheduledDeleteExtAuthReqCallbackId,
	);
}

impl scheduled_delete_ext_auth_req for super::RemoteReducers {
	fn scheduled_delete_ext_auth_req(
		&self, args: ExternalAuthenticationRequestExpirySchedule,
	) -> __sdk::Result<()> {
		self.imp.call_reducer(
			"scheduled_delete_ext_auth_req",
			ScheduledDeleteExtAuthReqArgs { args },
		)
	}

	fn on_scheduled_delete_ext_auth_req(
		&self,
		mut callback: impl FnMut(
			&super::ReducerEventContext,
			&ExternalAuthenticationRequestExpirySchedule,
		) + Send
		+ 'static,
	) -> ScheduledDeleteExtAuthReqCallbackId {
		ScheduledDeleteExtAuthReqCallbackId(self.imp.on_reducer(
			"scheduled_delete_ext_auth_req",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer: super::Reducer::ScheduledDeleteExtAuthReq { args },
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, args)
			}),
		))
	}

	fn remove_on_scheduled_delete_ext_auth_req(
		&self, callback: ScheduledDeleteExtAuthReqCallbackId,
	) {
		self.imp
			.remove_on_reducer("scheduled_delete_ext_auth_req", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `scheduled_delete_ext_auth_req`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_scheduled_delete_ext_auth_req {
	/// Set the call-reducer flags for the reducer
	/// `scheduled_delete_ext_auth_req` to `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn scheduled_delete_ext_auth_req(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_scheduled_delete_ext_auth_req for super::SetReducerFlags {
	fn scheduled_delete_ext_auth_req(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("scheduled_delete_ext_auth_req", flags);
	}
}
