// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::{
	actor_id_type::ActorId, channel_metadata_type::ChannelMetadata,
	standalone_channel_type::StandaloneChannel,
};

/// Table handle for the table `standalone_channel`.
///
/// Obtain a handle from the
/// [`StandaloneChannelTableAccess::standalone_channel`] method on
/// [`super::RemoteTables`], like `ctx.db.standalone_channel()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.standalone_channel().on_insert(...)`.
pub struct StandaloneChannelTableHandle<'ctx> {
	imp: __sdk::TableHandle<StandaloneChannel>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `standalone_channel`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StandaloneChannelTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`StandaloneChannelTableHandle`], which mediates access to the
	/// table `standalone_channel`.
	fn standalone_channel(&self) -> StandaloneChannelTableHandle<'_>;
}

impl StandaloneChannelTableAccess for super::RemoteTables {
	fn standalone_channel(&self) -> StandaloneChannelTableHandle<'_> {
		StandaloneChannelTableHandle {
			imp: self
				.imp
				.get_table::<StandaloneChannel>("standalone_channel"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct StandaloneChannelInsertCallbackId(__sdk::CallbackId);
pub struct StandaloneChannelDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StandaloneChannelTableHandle<'ctx> {
	type DeleteCallbackId = StandaloneChannelDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = StandaloneChannelInsertCallbackId;
	type Row = StandaloneChannel;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = StandaloneChannel> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> StandaloneChannelInsertCallbackId {
		StandaloneChannelInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: StandaloneChannelInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> StandaloneChannelDeleteCallbackId {
		StandaloneChannelDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: StandaloneChannelDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<StandaloneChannel>("standalone_channel");
	_table.add_unique_constraint::<String>("id", |row| &row.id);
	_table.add_unique_constraint::<String>("canonical_alias", |row| &row.canonical_alias);
}
pub struct StandaloneChannelUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StandaloneChannelTableHandle<'ctx> {
	type UpdateCallbackId = StandaloneChannelUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> StandaloneChannelUpdateCallbackId {
		StandaloneChannelUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: StandaloneChannelUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StandaloneChannel>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<StandaloneChannel>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `standalone_channel`,
/// which allows point queries on the field of the same name
/// via the [`StandaloneChannelIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.standalone_channel().id().find(...)`.
pub struct StandaloneChannelIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<StandaloneChannel, String>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StandaloneChannelTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `standalone_channel`.
	pub fn id(&self) -> StandaloneChannelIdUnique<'ctx> {
		StandaloneChannelIdUnique {
			imp:     self.imp.get_unique_constraint::<String>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> StandaloneChannelIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &String) -> Option<StandaloneChannel> {
		self.imp.find(col_val)
	}
}

/// Access to the `canonical_alias` unique index on the table
/// `standalone_channel`, which allows point queries on the field of the same
/// name via the [`StandaloneChannelCanonicalAliasUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.standalone_channel().canonical_alias().find(...)`.
pub struct StandaloneChannelCanonicalAliasUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<StandaloneChannel, String>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StandaloneChannelTableHandle<'ctx> {
	/// Get a handle on the `canonical_alias` unique index on the table
	/// `standalone_channel`.
	pub fn canonical_alias(&self) -> StandaloneChannelCanonicalAliasUnique<'ctx> {
		StandaloneChannelCanonicalAliasUnique {
			imp:     self.imp.get_unique_constraint::<String>("canonical_alias"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> StandaloneChannelCanonicalAliasUnique<'ctx> {
	/// Find the subscribed row whose `canonical_alias` column value is equal to
	/// `col_val`, if such a row is present in the client cache.
	pub fn find(&self, col_val: &String) -> Option<StandaloneChannel> {
		self.imp.find(col_val)
	}
}
