[package]
name = "telecrow-rs"
description = "Akaia Labs crow.d Rust telegram bridge"
version = "0.1.0"
edition = "2024"


# Subject to be extracted into a separate package, resides here for the initial prototyping
[[bin]]
name = "telecrow"
path = "src/main.rs"


[dependencies]
# crow.d
crowlink-rs.workspace = true

# External packages
spacetimedb-sdk.workspace = true
hex.workspace = true
