[package]
name = "telecrow-rs"
description = "Akaia Labs crow.d Rust telegram bridge"
version = "0.1.0"
edition = "2024"
default-run = "telecrow"

# Subject to be extracted into a separate package, resides here for the initial prototyping
[[bin]]
name = "telecrow"
path = "src/main.rs"


[dependencies]
# crow.d
crowtocol_rs.workspace = true

# External packages
dotenvy.workspace = true
hex.workspace = true
log.workspace = true
pretty_env_logger.workspace = true
spacetimedb-sdk.workspace = true
teloxide.workspace = true
tokio.workspace = true
