// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::external_actor_reference_type::ExternalActorReference;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateExternalAuthenticationRequestArgs {
	pub exref: ExternalActorReference,
}

impl From<CreateExternalAuthenticationRequestArgs> for super::Reducer {
	fn from(args: CreateExternalAuthenticationRequestArgs) -> Self {
		Self::CreateExternalAuthenticationRequest { exref: args.exref }
	}
}

impl __sdk::InModule for CreateExternalAuthenticationRequestArgs {
	type Module = super::RemoteModule;
}

pub struct CreateExternalAuthenticationRequestCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer
/// `create_external_authentication_request`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_external_authentication_request {
	/// Request that the remote module invoke the reducer
	/// `create_external_authentication_request` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_create_external_authentication_request`] callbacks.
	fn create_external_authentication_request(
		&self, exref: ExternalActorReference,
	) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `create_external_authentication_request`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`CreateExternalAuthenticationRequestCallbackId`] can be
	/// passed to [`Self::remove_on_create_external_authentication_request`] to
	/// cancel the callback.
	fn on_create_external_authentication_request(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &ExternalActorReference) + Send + 'static,
	) -> CreateExternalAuthenticationRequestCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_create_external_authentication_request`], causing it not to
	/// run in the future.
	fn remove_on_create_external_authentication_request(
		&self, callback: CreateExternalAuthenticationRequestCallbackId,
	);
}

impl create_external_authentication_request for super::RemoteReducers {
	fn create_external_authentication_request(
		&self, exref: ExternalActorReference,
	) -> __sdk::Result<()> {
		self.imp.call_reducer(
			"create_external_authentication_request",
			CreateExternalAuthenticationRequestArgs { exref },
		)
	}

	fn on_create_external_authentication_request(
		&self,
		mut callback: impl FnMut(&super::ReducerEventContext, &ExternalActorReference) + Send + 'static,
	) -> CreateExternalAuthenticationRequestCallbackId {
		CreateExternalAuthenticationRequestCallbackId(self.imp.on_reducer(
			"create_external_authentication_request",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer: super::Reducer::CreateExternalAuthenticationRequest { exref },
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, exref)
			}),
		))
	}

	fn remove_on_create_external_authentication_request(
		&self, callback: CreateExternalAuthenticationRequestCallbackId,
	) {
		self.imp
			.remove_on_reducer("create_external_authentication_request", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `create_external_authentication_request`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_create_external_authentication_request {
	/// Set the call-reducer flags for the reducer
	/// `create_external_authentication_request` to `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn create_external_authentication_request(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_external_authentication_request for super::SetReducerFlags {
	fn create_external_authentication_request(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("create_external_authentication_request", flags);
	}
}
