// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::channel_id_type::ChannelId;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteChannelArgs {
	pub channel_id: ChannelId,
}

impl From<DeleteChannelArgs> for super::Reducer {
	fn from(args: DeleteChannelArgs) -> Self {
		Self::DeleteChannel {
			channel_id: args.channel_id,
		}
	}
}

impl __sdk::InModule for DeleteChannelArgs {
	type Module = super::RemoteModule;
}

pub struct DeleteChannelCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_channel {
	/// Request that the remote module invoke the reducer `delete_channel` to
	/// run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_delete_channel`] callbacks.
	fn delete_channel(&self, channel_id: ChannelId) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `delete_channel`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`DeleteChannelCallbackId`] can be passed to
	/// [`Self::remove_on_delete_channel`] to cancel the callback.
	fn on_delete_channel(
		&self, callback: impl FnMut(&super::ReducerEventContext, &ChannelId) + Send + 'static,
	) -> DeleteChannelCallbackId;
	/// Cancel a callback previously registered by [`Self::on_delete_channel`],
	/// causing it not to run in the future.
	fn remove_on_delete_channel(&self, callback: DeleteChannelCallbackId);
}

impl delete_channel for super::RemoteReducers {
	fn delete_channel(&self, channel_id: ChannelId) -> __sdk::Result<()> {
		self.imp
			.call_reducer("delete_channel", DeleteChannelArgs { channel_id })
	}

	fn on_delete_channel(
		&self, mut callback: impl FnMut(&super::ReducerEventContext, &ChannelId) + Send + 'static,
	) -> DeleteChannelCallbackId {
		DeleteChannelCallbackId(self.imp.on_reducer(
			"delete_channel",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer: super::Reducer::DeleteChannel { channel_id },
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, channel_id)
			}),
		))
	}

	fn remove_on_delete_channel(&self, callback: DeleteChannelCallbackId) {
		self.imp.remove_on_reducer("delete_channel", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_channel`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_delete_channel {
	/// Set the call-reducer flags for the reducer `delete_channel` to `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn delete_channel(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_channel for super::SetReducerFlags {
	fn delete_channel(&self, flags: __ws::CallReducerFlags) {
		self.imp.set_call_reducer_flags("delete_channel", flags);
	}
}
