// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ExternalActor {
	pub id:       String,
	pub callsign: Option<String>,
	pub owner_id: Option<__sdk::Identity>,
	pub profile:  Option<i128>,
}

impl __sdk::InModule for ExternalActor {
	type Module = super::RemoteModule;
}
