// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::external_actor_reference_type::ExternalActorReference;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InitiateExternalAuthenticationArgs {
	pub exref: ExternalActorReference,
}

impl From<InitiateExternalAuthenticationArgs> for super::Reducer {
	fn from(args: InitiateExternalAuthenticationArgs) -> Self {
		Self::InitiateExternalAuthentication { exref: args.exref }
	}
}

impl __sdk::InModule for InitiateExternalAuthenticationArgs {
	type Module = super::RemoteModule;
}

pub struct InitiateExternalAuthenticationCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer
/// `initiate_external_authentication`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait initiate_external_authentication {
	/// Request that the remote module invoke the reducer
	/// `initiate_external_authentication` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_initiate_external_authentication`] callbacks.
	fn initiate_external_authentication(&self, exref: ExternalActorReference) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `initiate_external_authentication`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`InitiateExternalAuthenticationCallbackId`] can be passed
	/// to [`Self::remove_on_initiate_external_authentication`] to cancel the
	/// callback.
	fn on_initiate_external_authentication(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &ExternalActorReference) + Send + 'static,
	) -> InitiateExternalAuthenticationCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_initiate_external_authentication`], causing it not to run in
	/// the future.
	fn remove_on_initiate_external_authentication(
		&self, callback: InitiateExternalAuthenticationCallbackId,
	);
}

impl initiate_external_authentication for super::RemoteReducers {
	fn initiate_external_authentication(&self, exref: ExternalActorReference) -> __sdk::Result<()> {
		self.imp.call_reducer(
			"initiate_external_authentication",
			InitiateExternalAuthenticationArgs { exref },
		)
	}

	fn on_initiate_external_authentication(
		&self,
		mut callback: impl FnMut(&super::ReducerEventContext, &ExternalActorReference) + Send + 'static,
	) -> InitiateExternalAuthenticationCallbackId {
		InitiateExternalAuthenticationCallbackId(self.imp.on_reducer(
			"initiate_external_authentication",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer: super::Reducer::InitiateExternalAuthentication { exref },
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, exref)
			}),
		))
	}

	fn remove_on_initiate_external_authentication(
		&self, callback: InitiateExternalAuthenticationCallbackId,
	) {
		self.imp
			.remove_on_reducer("initiate_external_authentication", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `initiate_external_authentication`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_initiate_external_authentication {
	/// Set the call-reducer flags for the reducer
	/// `initiate_external_authentication` to `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn initiate_external_authentication(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_initiate_external_authentication for super::SetReducerFlags {
	fn initiate_external_authentication(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("initiate_external_authentication", flags);
	}
}
