// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::external_account_reference_type::ExternalAccountReference;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MirrorExternalProfileArgs {
	pub reference: ExternalAccountReference,
}

impl From<MirrorExternalProfileArgs> for super::Reducer {
	fn from(args: MirrorExternalProfileArgs) -> Self {
		Self::MirrorExternalProfile {
			reference: args.reference,
		}
	}
}

impl __sdk::InModule for MirrorExternalProfileArgs {
	type Module = super::RemoteModule;
}

pub struct MirrorExternalProfileCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mirror_external_profile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mirror_external_profile {
	/// Request that the remote module invoke the reducer
	/// `mirror_external_profile` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_mirror_external_profile`] callbacks.
	fn mirror_external_profile(&self, reference: ExternalAccountReference) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `mirror_external_profile`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`MirrorExternalProfileCallbackId`] can be passed to
	/// [`Self::remove_on_mirror_external_profile`] to cancel the callback.
	fn on_mirror_external_profile(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &ExternalAccountReference) + Send + 'static,
	) -> MirrorExternalProfileCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_mirror_external_profile`], causing it not to run in the
	/// future.
	fn remove_on_mirror_external_profile(&self, callback: MirrorExternalProfileCallbackId);
}

impl mirror_external_profile for super::RemoteReducers {
	fn mirror_external_profile(&self, reference: ExternalAccountReference) -> __sdk::Result<()> {
		self.imp
			.call_reducer("mirror_external_profile", MirrorExternalProfileArgs {
				reference,
			})
	}

	fn on_mirror_external_profile(
		&self,
		mut callback: impl FnMut(&super::ReducerEventContext, &ExternalAccountReference)
		+ Send
		+ 'static,
	) -> MirrorExternalProfileCallbackId {
		MirrorExternalProfileCallbackId(self.imp.on_reducer(
			"mirror_external_profile",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer: super::Reducer::MirrorExternalProfile { reference },
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, reference)
			}),
		))
	}

	fn remove_on_mirror_external_profile(&self, callback: MirrorExternalProfileCallbackId) {
		self.imp
			.remove_on_reducer("mirror_external_profile", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `mirror_external_profile`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_mirror_external_profile {
	/// Set the call-reducer flags for the reducer `mirror_external_profile` to
	/// `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn mirror_external_profile(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_mirror_external_profile for super::SetReducerFlags {
	fn mirror_external_profile(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("mirror_external_profile", flags);
	}
}
