// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::channel_metadata_type::ChannelMetadata;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterSuperchannelArgs {
	pub channel_id: String,
	pub alias:      String,
	pub metadata:   Option<ChannelMetadata>,
}

impl From<RegisterSuperchannelArgs> for super::Reducer {
	fn from(args: RegisterSuperchannelArgs) -> Self {
		Self::RegisterSuperchannel {
			channel_id: args.channel_id,
			alias:      args.alias,
			metadata:   args.metadata,
		}
	}
}

impl __sdk::InModule for RegisterSuperchannelArgs {
	type Module = super::RemoteModule;
}

pub struct RegisterSuperchannelCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_superchannel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_superchannel {
	/// Request that the remote module invoke the reducer
	/// `register_superchannel` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_register_superchannel`] callbacks.
	fn register_superchannel(
		&self, channel_id: String, alias: String, metadata: Option<ChannelMetadata>,
	) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `register_superchannel`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`RegisterSuperchannelCallbackId`] can be passed to
	/// [`Self::remove_on_register_superchannel`] to cancel the callback.
	fn on_register_superchannel(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &String, &String, &Option<ChannelMetadata>)
		+ Send
		+ 'static,
	) -> RegisterSuperchannelCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_register_superchannel`], causing it not to run in the
	/// future.
	fn remove_on_register_superchannel(&self, callback: RegisterSuperchannelCallbackId);
}

impl register_superchannel for super::RemoteReducers {
	fn register_superchannel(
		&self, channel_id: String, alias: String, metadata: Option<ChannelMetadata>,
	) -> __sdk::Result<()> {
		self.imp
			.call_reducer("register_superchannel", RegisterSuperchannelArgs {
				channel_id,
				alias,
				metadata,
			})
	}

	fn on_register_superchannel(
		&self,
		mut callback: impl FnMut(
			&super::ReducerEventContext,
			&String,
			&String,
			&Option<ChannelMetadata>,
		) + Send
		+ 'static,
	) -> RegisterSuperchannelCallbackId {
		RegisterSuperchannelCallbackId(self.imp.on_reducer(
			"register_superchannel",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer:
								super::Reducer::RegisterSuperchannel {
									channel_id,
									alias,
									metadata,
								},
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, channel_id, alias, metadata)
			}),
		))
	}

	fn remove_on_register_superchannel(&self, callback: RegisterSuperchannelCallbackId) {
		self.imp
			.remove_on_reducer("register_superchannel", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `register_superchannel`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_register_superchannel {
	/// Set the call-reducer flags for the reducer `register_superchannel` to
	/// `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn register_superchannel(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_register_superchannel for super::SetReducerFlags {
	fn register_superchannel(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("register_superchannel", flags);
	}
}
