// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::{actor_id_type::ActorId, channel_metadata_type::ChannelMetadata};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SubordinateChannel {
	pub id:              String,
	pub canonical_alias: String,
	pub creator:         __sdk::Identity,
	pub created_at:      __sdk::Timestamp,
	pub updated_at:      __sdk::Timestamp,
	pub metadata:        ChannelMetadata,
	pub members:         Vec<ActorId>,
	pub superchannel:    String,
}

impl __sdk::InModule for SubordinateChannel {
	type Module = super::RemoteModule;
}
