// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::external_actor_reference_type::ExternalActorReference;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnlinkExternalActorArgs {
	pub exref: ExternalActorReference,
}

impl From<UnlinkExternalActorArgs> for super::Reducer {
	fn from(args: UnlinkExternalActorArgs) -> Self {
		Self::UnlinkExternalActor { exref: args.exref }
	}
}

impl __sdk::InModule for UnlinkExternalActorArgs {
	type Module = super::RemoteModule;
}

pub struct UnlinkExternalActorCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unlink_external_actor`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unlink_external_actor {
	/// Request that the remote module invoke the reducer
	/// `unlink_external_actor` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_unlink_external_actor`] callbacks.
	fn unlink_external_actor(&self, exref: ExternalActorReference) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `unlink_external_actor`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`UnlinkExternalActorCallbackId`] can be passed to
	/// [`Self::remove_on_unlink_external_actor`] to cancel the callback.
	fn on_unlink_external_actor(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &ExternalActorReference) + Send + 'static,
	) -> UnlinkExternalActorCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_unlink_external_actor`], causing it not to run in the
	/// future.
	fn remove_on_unlink_external_actor(&self, callback: UnlinkExternalActorCallbackId);
}

impl unlink_external_actor for super::RemoteReducers {
	fn unlink_external_actor(&self, exref: ExternalActorReference) -> __sdk::Result<()> {
		self.imp
			.call_reducer("unlink_external_actor", UnlinkExternalActorArgs { exref })
	}

	fn on_unlink_external_actor(
		&self,
		mut callback: impl FnMut(&super::ReducerEventContext, &ExternalActorReference) + Send + 'static,
	) -> UnlinkExternalActorCallbackId {
		UnlinkExternalActorCallbackId(self.imp.on_reducer(
			"unlink_external_actor",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer: super::Reducer::UnlinkExternalActor { exref },
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, exref)
			}),
		))
	}

	fn remove_on_unlink_external_actor(&self, callback: UnlinkExternalActorCallbackId) {
		self.imp
			.remove_on_reducer("unlink_external_actor", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `unlink_external_actor`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_unlink_external_actor {
	/// Set the call-reducer flags for the reducer `unlink_external_actor` to
	/// `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn unlink_external_actor(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_unlink_external_actor for super::SetReducerFlags {
	fn unlink_external_actor(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("unlink_external_actor", flags);
	}
}
