// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::tp_account_reference_type::TpAccountReference;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnlinkTpAccountArgs {
	pub reference: TpAccountReference,
}

impl From<UnlinkTpAccountArgs> for super::Reducer {
	fn from(args: UnlinkTpAccountArgs) -> Self {
		Self::UnlinkTpAccount {
			reference: args.reference,
		}
	}
}

impl __sdk::InModule for UnlinkTpAccountArgs {
	type Module = super::RemoteModule;
}

pub struct UnlinkTpAccountCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unlink_tp_account`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unlink_tp_account {
	/// Request that the remote module invoke the reducer `unlink_tp_account` to
	/// run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_unlink_tp_account`] callbacks.
	fn unlink_tp_account(&self, reference: TpAccountReference) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `unlink_tp_account`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`UnlinkTpAccountCallbackId`] can be passed to
	/// [`Self::remove_on_unlink_tp_account`] to cancel the callback.
	fn on_unlink_tp_account(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &TpAccountReference) + Send + 'static,
	) -> UnlinkTpAccountCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_unlink_tp_account`], causing it not to run in the future.
	fn remove_on_unlink_tp_account(&self, callback: UnlinkTpAccountCallbackId);
}

impl unlink_tp_account for super::RemoteReducers {
	fn unlink_tp_account(&self, reference: TpAccountReference) -> __sdk::Result<()> {
		self.imp
			.call_reducer("unlink_tp_account", UnlinkTpAccountArgs { reference })
	}

	fn on_unlink_tp_account(
		&self,
		mut callback: impl FnMut(&super::ReducerEventContext, &TpAccountReference) + Send + 'static,
	) -> UnlinkTpAccountCallbackId {
		UnlinkTpAccountCallbackId(self.imp.on_reducer(
			"unlink_tp_account",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer: super::Reducer::UnlinkTpAccount { reference },
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, reference)
			}),
		))
	}

	fn remove_on_unlink_tp_account(&self, callback: UnlinkTpAccountCallbackId) {
		self.imp.remove_on_reducer("unlink_tp_account", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `unlink_tp_account`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_unlink_tp_account {
	/// Set the call-reducer flags for the reducer `unlink_tp_account` to
	/// `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn unlink_tp_account(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_unlink_tp_account for super::SetReducerFlags {
	fn unlink_tp_account(&self, flags: __ws::CallReducerFlags) {
		self.imp.set_call_reducer_flags("unlink_tp_account", flags);
	}
}
