// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ResolveAccountLinkRequestArgs {
	pub request_id:  i128,
	pub is_approved: bool,
}

impl From<ResolveAccountLinkRequestArgs> for super::Reducer {
	fn from(args: ResolveAccountLinkRequestArgs) -> Self {
		Self::ResolveAccountLinkRequest {
			request_id:  args.request_id,
			is_approved: args.is_approved,
		}
	}
}

impl __sdk::InModule for ResolveAccountLinkRequestArgs {
	type Module = super::RemoteModule;
}

pub struct ResolveAccountLinkRequestCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `resolve_account_link_request`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait resolve_account_link_request {
	/// Request that the remote module invoke the reducer
	/// `resolve_account_link_request` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_resolve_account_link_request`] callbacks.
	fn resolve_account_link_request(
		&self, request_id: i128, is_approved: bool,
	) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `resolve_account_link_request`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`ResolveAccountLinkRequestCallbackId`] can be passed to
	/// [`Self::remove_on_resolve_account_link_request`] to cancel the
	/// callback.
	fn on_resolve_account_link_request(
		&self, callback: impl FnMut(&super::ReducerEventContext, &i128, &bool) + Send + 'static,
	) -> ResolveAccountLinkRequestCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_resolve_account_link_request`], causing it not to run in the
	/// future.
	fn remove_on_resolve_account_link_request(&self, callback: ResolveAccountLinkRequestCallbackId);
}

impl resolve_account_link_request for super::RemoteReducers {
	fn resolve_account_link_request(
		&self, request_id: i128, is_approved: bool,
	) -> __sdk::Result<()> {
		self.imp.call_reducer(
			"resolve_account_link_request",
			ResolveAccountLinkRequestArgs {
				request_id,
				is_approved,
			},
		)
	}

	fn on_resolve_account_link_request(
		&self, mut callback: impl FnMut(&super::ReducerEventContext, &i128, &bool) + Send + 'static,
	) -> ResolveAccountLinkRequestCallbackId {
		ResolveAccountLinkRequestCallbackId(self.imp.on_reducer(
			"resolve_account_link_request",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer:
								super::Reducer::ResolveAccountLinkRequest {
									request_id,
									is_approved,
								},
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, request_id, is_approved)
			}),
		))
	}

	fn remove_on_resolve_account_link_request(
		&self, callback: ResolveAccountLinkRequestCallbackId,
	) {
		self.imp
			.remove_on_reducer("resolve_account_link_request", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `resolve_account_link_request`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_resolve_account_link_request {
	/// Set the call-reducer flags for the reducer
	/// `resolve_account_link_request` to `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn resolve_account_link_request(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_resolve_account_link_request for super::SetReducerFlags {
	fn resolve_account_link_request(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("resolve_account_link_request", flags);
	}
}
