// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::tp_account_type::TpAccount;

/// Table handle for the table `tp_account`.
///
/// Obtain a handle from the [`TpAccountTableAccess::tp_account`] method on
/// [`super::RemoteTables`], like `ctx.db.tp_account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tp_account().on_insert(...)`.
pub struct TpAccountTableHandle<'ctx> {
	imp: __sdk::TableHandle<TpAccount>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tp_account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TpAccountTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`TpAccountTableHandle`], which mediates access to the table
	/// `tp_account`.
	fn tp_account(&self) -> TpAccountTableHandle<'_>;
}

impl TpAccountTableAccess for super::RemoteTables {
	fn tp_account(&self) -> TpAccountTableHandle<'_> {
		TpAccountTableHandle {
			imp: self.imp.get_table::<TpAccount>("tp_account"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct TpAccountInsertCallbackId(__sdk::CallbackId);
pub struct TpAccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TpAccountTableHandle<'ctx> {
	type DeleteCallbackId = TpAccountDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = TpAccountInsertCallbackId;
	type Row = TpAccount;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = TpAccount> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> TpAccountInsertCallbackId {
		TpAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: TpAccountInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> TpAccountDeleteCallbackId {
		TpAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: TpAccountDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<TpAccount>("tp_account");
	_table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct TpAccountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TpAccountTableHandle<'ctx> {
	type UpdateCallbackId = TpAccountUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> TpAccountUpdateCallbackId {
		TpAccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: TpAccountUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TpAccount>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<TpAccount>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `tp_account`,
/// which allows point queries on the field of the same name
/// via the [`TpAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tp_account().id().find(...)`.
pub struct TpAccountIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<TpAccount, String>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TpAccountTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `tp_account`.
	pub fn id(&self) -> TpAccountIdUnique<'ctx> {
		TpAccountIdUnique {
			imp:     self.imp.get_unique_constraint::<String>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> TpAccountIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &String) -> Option<TpAccount> {
		self.imp.find(col_val)
	}
}
