// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::tp_account_reference_type::TpAccountReference;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateTpAccountCallsignArgs {
	pub reference: TpAccountReference,
	pub callsign:  Option<String>,
}

impl From<UpdateTpAccountCallsignArgs> for super::Reducer {
	fn from(args: UpdateTpAccountCallsignArgs) -> Self {
		Self::UpdateTpAccountCallsign {
			reference: args.reference,
			callsign:  args.callsign,
		}
	}
}

impl __sdk::InModule for UpdateTpAccountCallsignArgs {
	type Module = super::RemoteModule;
}

pub struct UpdateTpAccountCallsignCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_tp_account_callsign`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_tp_account_callsign {
	/// Request that the remote module invoke the reducer
	/// `update_tp_account_callsign` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_update_tp_account_callsign`] callbacks.
	fn update_tp_account_callsign(
		&self, reference: TpAccountReference, callsign: Option<String>,
	) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `update_tp_account_callsign`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`UpdateTpAccountCallsignCallbackId`] can be passed to
	/// [`Self::remove_on_update_tp_account_callsign`] to cancel the callback.
	fn on_update_tp_account_callsign(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &TpAccountReference, &Option<String>)
		+ Send
		+ 'static,
	) -> UpdateTpAccountCallsignCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_update_tp_account_callsign`], causing it not to run in the
	/// future.
	fn remove_on_update_tp_account_callsign(&self, callback: UpdateTpAccountCallsignCallbackId);
}

impl update_tp_account_callsign for super::RemoteReducers {
	fn update_tp_account_callsign(
		&self, reference: TpAccountReference, callsign: Option<String>,
	) -> __sdk::Result<()> {
		self.imp
			.call_reducer("update_tp_account_callsign", UpdateTpAccountCallsignArgs {
				reference,
				callsign,
			})
	}

	fn on_update_tp_account_callsign(
		&self,
		mut callback: impl FnMut(&super::ReducerEventContext, &TpAccountReference, &Option<String>)
		+ Send
		+ 'static,
	) -> UpdateTpAccountCallsignCallbackId {
		UpdateTpAccountCallsignCallbackId(self.imp.on_reducer(
			"update_tp_account_callsign",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer:
								super::Reducer::UpdateTpAccountCallsign {
									reference,
									callsign,
								},
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, reference, callsign)
			}),
		))
	}

	fn remove_on_update_tp_account_callsign(&self, callback: UpdateTpAccountCallsignCallbackId) {
		self.imp
			.remove_on_reducer("update_tp_account_callsign", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `update_tp_account_callsign`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_update_tp_account_callsign {
	/// Set the call-reducer flags for the reducer `update_tp_account_callsign`
	/// to `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn update_tp_account_callsign(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_tp_account_callsign for super::SetReducerFlags {
	fn update_tp_account_callsign(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("update_tp_account_callsign", flags);
	}
}
