[package]
name = "crowlink-rs"
description = "Akaia Labs crow.d Rust client library"
version = "0.1.0"
edition = "2021"

[lib]
name = "crowlink"
path = "src/lib.rs"

# Subject to be extracted into a separate package, resides here for the initial prototyping
[[bin]]
name = "crowchat"
path = "src/main.rs"

[dependencies]
spacetimedb-sdk.workspace = true
hex.workspace = true
