// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::{
	public_profile_metadata_type::PublicProfileMetadata,
	public_profile_owner_id_type::PublicProfileOwnerId, public_profile_type::PublicProfile,
};

/// Table handle for the table `public_profile`.
///
/// Obtain a handle from the [`PublicProfileTableAccess::public_profile`] method
/// on [`super::RemoteTables`], like `ctx.db.public_profile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.public_profile().on_insert(...)`.
pub struct PublicProfileTableHandle<'ctx> {
	imp: __sdk::TableHandle<PublicProfile>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `public_profile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PublicProfileTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`PublicProfileTableHandle`], which mediates access to the
	/// table `public_profile`.
	fn public_profile(&self) -> PublicProfileTableHandle<'_>;
}

impl PublicProfileTableAccess for super::RemoteTables {
	fn public_profile(&self) -> PublicProfileTableHandle<'_> {
		PublicProfileTableHandle {
			imp: self.imp.get_table::<PublicProfile>("public_profile"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct PublicProfileInsertCallbackId(__sdk::CallbackId);
pub struct PublicProfileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PublicProfileTableHandle<'ctx> {
	type DeleteCallbackId = PublicProfileDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = PublicProfileInsertCallbackId;
	type Row = PublicProfile;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = PublicProfile> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> PublicProfileInsertCallbackId {
		PublicProfileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: PublicProfileInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> PublicProfileDeleteCallbackId {
		PublicProfileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: PublicProfileDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<PublicProfile>("public_profile");
	_table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PublicProfileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PublicProfileTableHandle<'ctx> {
	type UpdateCallbackId = PublicProfileUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> PublicProfileUpdateCallbackId {
		PublicProfileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: PublicProfileUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PublicProfile>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<PublicProfile>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `public_profile`,
/// which allows point queries on the field of the same name
/// via the [`PublicProfileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.public_profile().id().find(...)`.
pub struct PublicProfileIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<PublicProfile, u64>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PublicProfileTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `public_profile`.
	pub fn id(&self) -> PublicProfileIdUnique<'ctx> {
		PublicProfileIdUnique {
			imp:     self.imp.get_unique_constraint::<u64>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> PublicProfileIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &u64) -> Option<PublicProfile> {
		self.imp.find(col_val)
	}
}
