[package]
name = "crowcomm"
description = "Akaia Labs crow.d client SDK in Rust"
version = "0.1.0"
edition = "2024"


[lib]
name = "crowcomm"
path = "src/lib.rs"


[dependencies]
hex.workspace = true
spacetimedb-sdk.workspace = true
strum.workspace = true
strum_macros.workspace = true
teloxide.workspace = true
