[package]
name = "crowcomm"
description = "Akaia Labs crow.d client SDK in Rust"
version = "0.1.0"
edition = "2024"


[lib]
name = "crowcomm"
path = "src/lib.rs"


[dependencies]
spacetimedb-sdk.workspace = true
hex.workspace = true
