[package]
name = "crowdcomm_sdk"
description = "Akaia Labs subsystem SDK"
version = "0.3.0"
edition = "2024"


[lib]
name = "crowdcomm_sdk"
path = "src/lib.rs"


[dependencies]
# Internal dependencies
corvutils.workspace = true

# External dependencies
dotenvy.workspace = true
hex.workspace = true
serde.workspace = true
serde-env.workspace = true
spacetimedb-sdk.workspace = true
strum.workspace = true
strum_macros.workspace = true
teloxide.workspace = true
