// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::account_link_request_type::AccountLinkRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportAccountLinkResolutionArgs {
	pub request:     AccountLinkRequest,
	pub is_approved: bool,
}

impl From<ReportAccountLinkResolutionArgs> for super::Reducer {
	fn from(args: ReportAccountLinkResolutionArgs) -> Self {
		Self::ReportAccountLinkResolution {
			request:     args.request,
			is_approved: args.is_approved,
		}
	}
}

impl __sdk::InModule for ReportAccountLinkResolutionArgs {
	type Module = super::RemoteModule;
}

pub struct ReportAccountLinkResolutionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_account_link_resolution`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_account_link_resolution {
	/// Request that the remote module invoke the reducer
	/// `report_account_link_resolution` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_report_account_link_resolution`] callbacks.
	fn report_account_link_resolution(
		&self, request: AccountLinkRequest, is_approved: bool,
	) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `report_account_link_resolution`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`ReportAccountLinkResolutionCallbackId`] can be passed to
	/// [`Self::remove_on_report_account_link_resolution`] to cancel the
	/// callback.
	fn on_report_account_link_resolution(
		&self,
		callback: impl FnMut(&super::ReducerEventContext, &AccountLinkRequest, &bool) + Send + 'static,
	) -> ReportAccountLinkResolutionCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_report_account_link_resolution`], causing it not to run in
	/// the future.
	fn remove_on_report_account_link_resolution(
		&self, callback: ReportAccountLinkResolutionCallbackId,
	);
}

impl report_account_link_resolution for super::RemoteReducers {
	fn report_account_link_resolution(
		&self, request: AccountLinkRequest, is_approved: bool,
	) -> __sdk::Result<()> {
		self.imp.call_reducer(
			"report_account_link_resolution",
			ReportAccountLinkResolutionArgs {
				request,
				is_approved,
			},
		)
	}

	fn on_report_account_link_resolution(
		&self,
		mut callback: impl FnMut(&super::ReducerEventContext, &AccountLinkRequest, &bool)
		+ Send
		+ 'static,
	) -> ReportAccountLinkResolutionCallbackId {
		ReportAccountLinkResolutionCallbackId(self.imp.on_reducer(
			"report_account_link_resolution",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer:
								super::Reducer::ReportAccountLinkResolution {
									request,
									is_approved,
								},
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, request, is_approved)
			}),
		))
	}

	fn remove_on_report_account_link_resolution(
		&self, callback: ReportAccountLinkResolutionCallbackId,
	) {
		self.imp
			.remove_on_reducer("report_account_link_resolution", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `report_account_link_resolution`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_report_account_link_resolution {
	/// Set the call-reducer flags for the reducer
	/// `report_account_link_resolution` to `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn report_account_link_resolution(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_report_account_link_resolution for super::SetReducerFlags {
	fn report_account_link_resolution(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("report_account_link_resolution", flags);
	}
}
