// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::text_channel_type::TextChannel;

/// Table handle for the table `text_channel`.
///
/// Obtain a handle from the [`TextChannelTableAccess::text_channel`] method on
/// [`super::RemoteTables`], like `ctx.db.text_channel()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.text_channel().on_insert(...)`.
pub struct TextChannelTableHandle<'ctx> {
	imp: __sdk::TableHandle<TextChannel>,
	ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `text_channel`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TextChannelTableAccess {
	#[allow(non_snake_case)]
	/// Obtain a [`TextChannelTableHandle`], which mediates access to the table
	/// `text_channel`.
	fn text_channel(&self) -> TextChannelTableHandle<'_>;
}

impl TextChannelTableAccess for super::RemoteTables {
	fn text_channel(&self) -> TextChannelTableHandle<'_> {
		TextChannelTableHandle {
			imp: self.imp.get_table::<TextChannel>("text_channel"),
			ctx: std::marker::PhantomData,
		}
	}
}

pub struct TextChannelInsertCallbackId(__sdk::CallbackId);
pub struct TextChannelDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TextChannelTableHandle<'ctx> {
	type DeleteCallbackId = TextChannelDeleteCallbackId;
	type EventContext = super::EventContext;
	type InsertCallbackId = TextChannelInsertCallbackId;
	type Row = TextChannel;

	fn count(&self) -> u64 {
		self.imp.count()
	}

	fn iter(&self) -> impl Iterator<Item = TextChannel> + '_ {
		self.imp.iter()
	}

	fn on_insert(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> TextChannelInsertCallbackId {
		TextChannelInsertCallbackId(self.imp.on_insert(Box::new(callback)))
	}

	fn remove_on_insert(&self, callback: TextChannelInsertCallbackId) {
		self.imp.remove_on_insert(callback.0)
	}

	fn on_delete(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
	) -> TextChannelDeleteCallbackId {
		TextChannelDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
	}

	fn remove_on_delete(&self, callback: TextChannelDeleteCallbackId) {
		self.imp.remove_on_delete(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
	let _table = client_cache.get_or_make_table::<TextChannel>("text_channel");
	_table.add_unique_constraint::<i128>("id", |row| &row.id);
}
pub struct TextChannelUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TextChannelTableHandle<'ctx> {
	type UpdateCallbackId = TextChannelUpdateCallbackId;

	fn on_update(
		&self, callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
	) -> TextChannelUpdateCallbackId {
		TextChannelUpdateCallbackId(self.imp.on_update(Box::new(callback)))
	}

	fn remove_on_update(&self, callback: TextChannelUpdateCallbackId) {
		self.imp.remove_on_update(callback.0)
	}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
	raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TextChannel>> {
	__sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
		__sdk::InternalError::failed_parse("TableUpdate<TextChannel>", "TableUpdate")
			.with_cause(e)
			.into()
	})
}

/// Access to the `id` unique index on the table `text_channel`,
/// which allows point queries on the field of the same name
/// via the [`TextChannelIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.text_channel().id().find(...)`.
pub struct TextChannelIdUnique<'ctx> {
	imp:     __sdk::UniqueConstraintHandle<TextChannel, i128>,
	phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TextChannelTableHandle<'ctx> {
	/// Get a handle on the `id` unique index on the table `text_channel`.
	pub fn id(&self) -> TextChannelIdUnique<'ctx> {
		TextChannelIdUnique {
			imp:     self.imp.get_unique_constraint::<i128>("id"),
			phantom: std::marker::PhantomData,
		}
	}
}

impl<'ctx> TextChannelIdUnique<'ctx> {
	/// Find the subscribed row whose `id` column value is equal to `col_val`,
	/// if such a row is present in the client cache.
	pub fn find(&self, col_val: &i128) -> Option<TextChannel> {
		self.imp.find(col_val)
	}
}
