// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::{
	account_profile_metadata_type::AccountProfileMetadata,
	tp_account_reference_type::TpAccountReference,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateTpAccountProfileArgs {
	pub reference: TpAccountReference,
	pub metadata:  Option<AccountProfileMetadata>,
}

impl From<UpdateTpAccountProfileArgs> for super::Reducer {
	fn from(args: UpdateTpAccountProfileArgs) -> Self {
		Self::UpdateTpAccountProfile {
			reference: args.reference,
			metadata:  args.metadata,
		}
	}
}

impl __sdk::InModule for UpdateTpAccountProfileArgs {
	type Module = super::RemoteModule;
}

pub struct UpdateTpAccountProfileCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_tp_account_profile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_tp_account_profile {
	/// Request that the remote module invoke the reducer
	/// `update_tp_account_profile` to run as soon as possible.
	///
	/// This method returns immediately, and errors only if we are unable to
	/// send the request. The reducer will run asynchronously in the future,
	///  and its status can be observed by listening for
	/// [`Self::on_update_tp_account_profile`] callbacks.
	fn update_tp_account_profile(
		&self, reference: TpAccountReference, metadata: Option<AccountProfileMetadata>,
	) -> __sdk::Result<()>;
	/// Register a callback to run whenever we are notified of an invocation of
	/// the reducer `update_tp_account_profile`.
	///
	/// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the
	/// [`super::ReducerEventContext`] to determine the reducer's status.
	///
	/// The returned [`UpdateTpAccountProfileCallbackId`] can be passed to
	/// [`Self::remove_on_update_tp_account_profile`] to cancel the callback.
	fn on_update_tp_account_profile(
		&self,
		callback: impl FnMut(
			&super::ReducerEventContext,
			&TpAccountReference,
			&Option<AccountProfileMetadata>,
		) + Send
		+ 'static,
	) -> UpdateTpAccountProfileCallbackId;
	/// Cancel a callback previously registered by
	/// [`Self::on_update_tp_account_profile`], causing it not to run in the
	/// future.
	fn remove_on_update_tp_account_profile(&self, callback: UpdateTpAccountProfileCallbackId);
}

impl update_tp_account_profile for super::RemoteReducers {
	fn update_tp_account_profile(
		&self, reference: TpAccountReference, metadata: Option<AccountProfileMetadata>,
	) -> __sdk::Result<()> {
		self.imp
			.call_reducer("update_tp_account_profile", UpdateTpAccountProfileArgs {
				reference,
				metadata,
			})
	}

	fn on_update_tp_account_profile(
		&self,
		mut callback: impl FnMut(
			&super::ReducerEventContext,
			&TpAccountReference,
			&Option<AccountProfileMetadata>,
		) + Send
		+ 'static,
	) -> UpdateTpAccountProfileCallbackId {
		UpdateTpAccountProfileCallbackId(self.imp.on_reducer(
			"update_tp_account_profile",
			Box::new(move |ctx: &super::ReducerEventContext| {
				let super::ReducerEventContext {
					event:
						__sdk::ReducerEvent {
							reducer:
								super::Reducer::UpdateTpAccountProfile {
									reference,
									metadata,
								},
							..
						},
					..
				} = ctx
				else {
					unreachable!()
				};
				callback(ctx, reference, metadata)
			}),
		))
	}

	fn remove_on_update_tp_account_profile(&self, callback: UpdateTpAccountProfileCallbackId) {
		self.imp
			.remove_on_reducer("update_tp_account_profile", callback.0)
	}
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer
/// `update_tp_account_profile`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version
/// bump.
pub trait set_flags_for_update_tp_account_profile {
	/// Set the call-reducer flags for the reducer `update_tp_account_profile`
	/// to `flags`.
	///
	/// This type is currently unstable and may be removed without a major
	/// version bump.
	fn update_tp_account_profile(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_tp_account_profile for super::SetReducerFlags {
	fn update_tp_account_profile(&self, flags: __ws::CallReducerFlags) {
		self.imp
			.set_call_reducer_flags("update_tp_account_profile", flags);
	}
}
